// brand/Bloqr Design System/ui_kits/landing/Hero.jsx
function Hero({ onWaitlist }) {
  const stats = [
    { value: 'AI', unit: '-focused', label: 'Plain English rules' },
    { value: '', unit: 'BYO', label: 'Vendor-agnostic · No lock-in' },
    { value: 'Real', unit: 'time', label: 'AI-powered threat intel' },
    { value: '', unit: '11', label: 'Filter transformations' },
  ];

  return (
    <section style={{ position: 'relative', padding: '72px 0 80px', textAlign: 'center', overflow: 'hidden' }}>
      <div aria-hidden style={{
        position: 'absolute', top: 0, left: '50%', transform: 'translateX(-50%)',
        width: 900, height: 560, pointerEvents: 'none',
        background: 'radial-gradient(ellipse at center, rgba(255,85,0,0.10) 0%, transparent 70%)',
      }} />
      <div aria-hidden style={{
        position: 'absolute', top: 120, right: '10%', width: 500, height: 300, pointerEvents: 'none',
        background: 'radial-gradient(ellipse at center, rgba(0,212,255,0.06) 0%, transparent 70%)',
      }} />

      <div style={{ maxWidth: 1200, margin: '0 auto', padding: '0 24px', position: 'relative' }}>
        <Pill tone="orange" dot>Set it. Bloqr it. Forget it.</Pill>

        <h1 style={{
          fontFamily: 'var(--font-display)',
          fontSize: 'clamp(2.5rem, 6vw, 5rem)', fontWeight: 800,
          lineHeight: 1.05, letterSpacing: '-0.03em',
          maxWidth: 880, margin: '32px auto 24px', color: 'var(--fg-1)',
        }}>
          Internet Hygiene:<br/>
          <em style={{
            fontStyle: 'normal',
            background: 'linear-gradient(135deg, var(--orange-500) 0%, #FF8833 100%)',
            WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent',
            backgroundClip: 'text',
          }}>Automated.</em>
        </h1>

        <p style={{
          fontSize: 'clamp(1rem, 2vw, 1.2rem)', color: 'var(--fg-2)',
          maxWidth: 600, margin: '0 auto 28px', lineHeight: 1.6,
          fontFamily: 'var(--font-body)',
        }}>
          Bloqr blocks ads, trackers, and malware at the network level — across every
          device, every network, all at once. Tell Bloqr what you want in plain English.
          Bloqr handles the rest.
        </p>

        <div style={{
          display: 'inline-flex', alignItems: 'flex-start', gap: 10,
          maxWidth: 560, margin: '0 auto 40px', padding: '14px 20px',
          borderRadius: 12, border: '1px solid rgba(255, 85, 0, 0.2)',
          background: 'rgba(255, 85, 0, 0.05)',
          fontSize: '0.92rem', color: 'var(--fg-2)', lineHeight: 1.5, textAlign: 'left',
        }}>
          <span aria-hidden style={{ fontSize: 16 }}>🔌</span>
          <span><strong style={{ color: 'var(--fg-1)' }}>Bring your own vendor.</strong> Already on AdGuard, NextDNS, or Pi-hole? Keep it. Bloqr layers on top. Or let us handle everything — your choice, always.</span>
        </div>

        <div style={{ display: 'flex', justifyContent: 'center', gap: 12, flexWrap: 'wrap', marginBottom: 64 }}>
          <Button variant="primary" onClick={onWaitlist}>Get started free <span aria-hidden>→</span></Button>
          <Button variant="outline">Read the docs</Button>
          <Button variant="ghost">See how it works</Button>
        </div>

        <div style={{
          display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)',
          gap: 2, background: 'var(--border)', borderRadius: 16, overflow: 'hidden',
          border: '1px solid var(--border)', maxWidth: 920, margin: '0 auto',
        }}>
          {stats.map((s, i) => (
            <div key={i} style={{ background: 'var(--bg-surface)', padding: '24px 16px' }}>
              <div style={{
                fontFamily: 'var(--font-display)', fontSize: 28, fontWeight: 800,
                letterSpacing: '-0.02em', color: 'var(--fg-1)', lineHeight: 1,
              }}>
                {s.value && <span>{s.value}</span>}
                <span style={{ color: 'var(--orange-500)' }}>{s.unit}</span>
              </div>
              <div style={{
                fontSize: 12, color: 'var(--fg-2)', marginTop: 8,
                letterSpacing: '0.02em',
              }}>{s.label}</div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

Object.assign(window, { Hero });

// src/components/Hero.svelte
<script>
  import { LINKS } from '../config';
</script>

<section class="hero">
  <!-- Radial glow backdrop -->
  <div class="glow" aria-hidden="true"></div>

  <div class="container">
    <div class="badge">
      <span class="badge-dot" aria-hidden="true"></span>
      Set it. Bloqr it. Forget it.
    </div>

    <h1>Internet Hygiene:<br /><em>Automated.</em></h1>

    <p class="sub">
      Bloqr blocks ads, trackers, and malware at the network level — across every
      device, every network, all at once. Tell Bloqr what you want in plain English.
      Bloqr handles the rest.
    </p>

    <div class="byo-pill" aria-label="Vendor flexibility">
      <span class="byo-icon" aria-hidden="true">🔌</span>
      <span><strong>Bring your own vendor.</strong> Already on AdGuard, NextDNS, or Pi-hole? Keep it. Bloqr layers on top. Or let us handle everything — your choice, always.</span>
    </div>

    <div class="actions">
      <a href={LINKS.app} class="btn btn-primary" rel="noopener noreferrer" target="_blank">
        Get started free <span aria-hidden="true">→</span>
      </a>
      <a href={LINKS.docs} class="btn btn-outline" rel="noopener noreferrer" target="_blank">
        Read the docs
      </a>
      <a href="/#why" class="btn btn-ghost">
        See how it works
      </a>
    </div>

    <!-- Stats bar -->
    <div class="stats" role="list">
      <div class="stat" role="listitem">
        <span class="stat-value">AI<span>-focused</span></span>
        <span class="stat-label">Plain English rules</span>
      </div>
      <div class="stat" role="listitem">
        <span class="stat-value"><span>BYO</span></span>
        <span class="stat-label">Vendor-agnostic · No lock-in</span>
      </div>
      <div class="stat" role="listitem">
        <span class="stat-value">Real<span>time</span></span>
        <span class="stat-label">AI-powered threat intelligence</span>
      </div>
      <div class="stat" role="listitem">
        <span class="stat-value"><span>11</span></span>
        <span class="stat-label">Filter transformations</span>
      </div>
    </div>
  </div>
</section>

<style>
  .hero {
    padding: 72px 0 80px;
    text-align: center;
    position: relative;
    overflow: hidden;
  }

  .glow {
    position: absolute;
    top: 0; left: 50%;
    transform: translateX(-50%);
    width: 800px; height: 500px;
    background: radial-gradient(ellipse at center, rgba(255,85,0,0.08) 0%, transparent 70%);
    pointer-events: none;
  }

  .badge {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    padding: 6px 14px;
    border-radius: 9999px;
    border: 1px solid rgba(255, 85, 0, 0.3);
    background: rgba(255, 85, 0, 0.08);
    font-size: 12px;
    font-weight: 600;
    letter-spacing: 0.08em;
    color: var(--orange);
    text-transform: uppercase;
    margin-bottom: 32px;
  }

  .badge-dot {
    display: block;
    width: 6px; height: 6px;
    border-radius: 50%;
    background: var(--orange);
    animation: pulse 2s infinite;
  }

  @keyframes pulse {
    0%, 100% { opacity: 1; transform: scale(1); }
    50%       { opacity: 0.5; transform: scale(0.8); }
  }

  h1 {
    font-size: clamp(2.5rem, 6vw, 5rem);
    font-weight: 800;
    line-height: 1.05;
    letter-spacing: -0.03em;
    margin-bottom: 24px;
    max-width: 880px;
    margin-left: auto;
    margin-right: auto;
  }

  h1 em {
    font-style: normal;
    background: linear-gradient(135deg, var(--orange) 0%, #FF8833 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
  }

  .sub {
    font-size: clamp(1rem, 2vw, 1.2rem);
    color: var(--text-2);
    max-width: 600px;
    margin: 0 auto 28px;
    line-height: 1.6;
  }

  .byo-pill {
    display: inline-flex;
    align-items: flex-start;
    gap: 10px;
    max-width: 560px;
    margin: 0 auto 40px;
    padding: 14px 20px;
    border-radius: 12px;
    border: 1px solid rgba(255, 85, 0, 0.2);
    background: rgba(255, 85, 0, 0.05);
    font-size: 0.92rem;
    color: var(--text-2);
    line-height: 1.5;
    text-align: left;
  }

  .byo-pill strong {
    color: var(--text-1);
  }

  .byo-icon {
    font-size: 1.1rem;
    flex-shrink: 0;
    margin-top: 1px;
  }

  .actions {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 16px;
    flex-wrap: wrap;
    margin-bottom: 72px;
  }

  .pkg-link {
    font-family: var(--font-mono);
    font-size: 13px;
    color: var(--cyan);
  }

  .stats {
    display: flex;
    justify-content: center;
    gap: 48px;
    flex-wrap: wrap;
    padding: 32px 0;
    border-top: 1px solid var(--border);
    border-bottom: 1px solid var(--border);
  }

  .stat { text-align: center; }

  .stat-value {
    font-size: 2rem;
    font-weight: 800;
    letter-spacing: -0.03em;
    color: var(--text-1);
    display: block;
  }

  .stat-value span { color: var(--orange); }

  .stat-label {
    font-size: 12px;
    color: var(--text-3);
    letter-spacing: 0.08em;
    text-transform: uppercase;
    display: block;
    margin-top: 4px;
  }
</style>
