// brand/Bloqr Design System/ui_kits/landing/Nav.jsx
function Nav({ active, setActive, onWaitlist }) {
  const links = [
    { id: 'why', label: 'Why' },
    { id: 'how', label: 'How' },
    { id: 'features', label: 'Features' },
    { id: 'pricing', label: 'Pricing' },
  ];

  return (
    <nav style={{
      position: 'sticky', top: 0, zIndex: 50,
      background: 'rgba(7, 11, 20, 0.85)',
      backdropFilter: 'blur(16px)',
      WebkitBackdropFilter: 'blur(16px)',
      borderBottom: '1px solid var(--border)',
    }}>
      <div style={{
        maxWidth: 1200, margin: '0 auto', padding: '0 24px',
        height: 64, display: 'flex', alignItems: 'center', gap: 32,
      }}>
        <a href="#" style={{ display: 'flex', alignItems: 'center', gap: 12, textDecoration: 'none' }}>
          <Mark size={24} />
          <div style={{ lineHeight: 1 }}>
            <div style={{
              fontFamily: 'var(--font-display)', fontWeight: 700,
              fontSize: 17, letterSpacing: '-0.01em', color: 'var(--fg-1)',
            }}>Bloqr</div>
            <div style={{
              fontFamily: 'var(--font-mono)', fontSize: 9,
              color: 'var(--fg-3)', letterSpacing: '0.1em',
              textTransform: 'uppercase', marginTop: 3,
            }}>Internet Hygiene · Automated</div>
          </div>
        </a>

        <ul style={{
          display: 'flex', gap: 24, listStyle: 'none', margin: 0, padding: 0,
          marginLeft: 16,
        }}>
          {links.map((l) => (
            <li key={l.id}>
              <a
                href={`#${l.id}`}
                onClick={(e) => { e.preventDefault(); setActive(l.id); document.getElementById(l.id)?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }}
                style={{
                  fontSize: 14, fontWeight: 500,
                  color: active === l.id ? 'var(--fg-1)' : 'var(--fg-2)',
                  textDecoration: 'none', cursor: 'pointer',
                  transition: 'color 150ms var(--ease-out)',
                }}
                onMouseEnter={(e) => e.currentTarget.style.color = 'var(--fg-1)'}
                onMouseLeave={(e) => e.currentTarget.style.color = active === l.id ? 'var(--fg-1)' : 'var(--fg-2)'}
              >{l.label}</a>
            </li>
          ))}
        </ul>

        <div style={{ marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 8 }}>
          <a href="#vpn" style={{
            fontSize: 13, color: 'var(--cyan-500)', textDecoration: 'none',
            padding: '6px 10px', borderRadius: 6, fontWeight: 500,
          }}>VPN Myths</a>
          <Button variant="ghost" size="sm">Docs</Button>
          <Button variant="primary" size="sm" onClick={onWaitlist}>
            Launch App <span aria-hidden>→</span>
          </Button>
        </div>
      </div>
    </nav>
  );
}

Object.assign(window, { Nav });

// src/components/Nav.svelte
<script>
  import { onMount } from 'svelte';
  import { LINKS } from '../config';

  let scrolled  = $state(false);
  let menuOpen  = $state(false);
  let currentPath = $state('/');

  onMount(() => {
    currentPath = window.location.pathname;
    const handleScroll = () => { scrolled = window.scrollY > 10; };
    const handlePageLoad = () => { currentPath = window.location.pathname; };
    window.addEventListener('scroll', handleScroll, { passive: true });
    document.addEventListener('astro:page-load', handlePageLoad);
    return () => {
      window.removeEventListener('scroll', handleScroll);
      document.removeEventListener('astro:page-load', handlePageLoad);
    };
  });

  function closeMenu() { menuOpen = false; }
  function toggleMenu() { menuOpen = !menuOpen; }

  function isActive(href) {
    if (!href || href.startsWith('/#')) return false;
    return currentPath === href || currentPath.startsWith(href + '/');
  }
</script>

<nav class:scrolled class:menu-open={menuOpen} aria-label="Main navigation">
  <a href="#main-content" class="skip-to-content">Skip to main content</a>
  <div class="inner container">

    <!-- Logo -->
    <a href="/" class="logo" aria-label="Bloqr — home" onclick={closeMenu}>
      <div class="logo-icon" aria-hidden="true">
        <span class="bar bar-1"></span>
        <span class="bar bar-2"></span>
        <span class="bar bar-3"></span>
      </div>
      <div class="logo-text">
        <span class="logo-name">BLOQR</span>
        <span class="logo-sub">Internet Hygiene:<br/><span class="logo-sub-auto">Automated</span></span>
      </div>
    </a>

    <!-- Desktop links -->
    <ul class="nav-links" role="list">
      <li><a href="/#why">Why</a></li>
      <li><a href="/#how">How</a></li>
      <li><a href="/#audiences">Who</a></li>
      <li><a href="/#features">Features</a></li>
      <li><a href="/#pricing">Pricing</a></li>
      <li><a href={LINKS.vpnMyths} class="nav-myths" class:active={isActive(LINKS.vpnMyths)} aria-current={isActive(LINKS.vpnMyths) ? 'page' : undefined}>VPN Myths</a></li>
      <li><a href={LINKS.blog} class="nav-news" class:active={isActive(LINKS.blog)} aria-current={isActive(LINKS.blog) ? 'page' : undefined}>News</a></li>
      <li><a href={LINKS.changelog} class:active={isActive(LINKS.changelog)} aria-current={isActive(LINKS.changelog) ? 'page' : undefined}>Changelog</a></li>
      <li><a href={LINKS.about} class:active={isActive(LINKS.about)} aria-current={isActive(LINKS.about) ? 'page' : undefined}>About</a></li>
      <li><a href="/#waitlist" class="nav-highlight">Early Access</a></li>
    </ul>

    <!-- Desktop CTA -->
    <div class="nav-cta">
      <a href={LINKS.docs} class="btn btn-ghost btn-sm" rel="noopener noreferrer" target="_blank">Docs</a>
      <a href={LINKS.app} class="btn btn-primary btn-sm" rel="noopener noreferrer" target="_blank">
        Launch App <span aria-hidden="true">→</span>
      </a>
    </div>

    <!-- Hamburger button (mobile only) -->
    <button
      class="hamburger"
      onclick={toggleMenu}
      aria-expanded={menuOpen}
      aria-controls="mobile-menu"
      aria-label={menuOpen ? 'Close menu' : 'Open menu'}
    >
      <span class="ham-bar"></span>
      <span class="ham-bar"></span>
      <span class="ham-bar"></span>
    </button>

  </div>

  <!-- Mobile menu -->
  {#if menuOpen}
    <button
      type="button"
      class="mobile-backdrop"
      onclick={closeMenu}
      onkeydown={(e) => e.key === 'Escape' && closeMenu()}
      aria-label="Close navigation menu"
      tabindex="-1"
    ></button>
    <div id="mobile-menu" class="mobile-menu" role="dialog" aria-label="Navigation menu">
      <ul class="mobile-links" role="list">
        <li><a href="/#why"           onclick={closeMenu}>Why Bloqr</a></li>
        <li><a href="/#how"           onclick={closeMenu}>How it works</a></li>
        <li><a href="/#audiences"     onclick={closeMenu}>Who it's for</a></li>
        <li><a href="/#features"      onclick={closeMenu}>Features</a></li>
        <li><a href="/#pricing"       onclick={closeMenu}>Pricing</a></li>
        <li><a href={LINKS.vpnMyths}  onclick={closeMenu} class:active={isActive(LINKS.vpnMyths)} aria-current={isActive(LINKS.vpnMyths) ? 'page' : undefined}>VPN Myths</a></li>
        <li><a href={LINKS.blog}      onclick={closeMenu} class:active={isActive(LINKS.blog)} aria-current={isActive(LINKS.blog) ? 'page' : undefined}>News</a></li>
        <li><a href={LINKS.changelog} onclick={closeMenu} class:active={isActive(LINKS.changelog)} aria-current={isActive(LINKS.changelog) ? 'page' : undefined}>Changelog</a></li>
        <li><a href={LINKS.about}     onclick={closeMenu} class:active={isActive(LINKS.about)} aria-current={isActive(LINKS.about) ? 'page' : undefined}>About</a></li>
        <li class="mobile-divider" aria-hidden="true"></li>
        <li><a href="/#waitlist" class="mobile-highlight" onclick={closeMenu}>Join Early Access →</a></li>
      </ul>
      <div class="mobile-footer">
        <a href={LINKS.docs} class="btn btn-outline btn-sm" rel="noopener noreferrer" target="_blank" onclick={closeMenu}>Docs</a>
        <a href={LINKS.app} class="btn btn-primary btn-sm" rel="noopener noreferrer" target="_blank" onclick={closeMenu}>
          Launch App →
        </a>
      </div>
    </div>
  {/if}
</nav>

<style>
  nav {
    position: sticky;
    top: 0;
    z-index: 100;
    border-bottom: 1px solid transparent;
    transition: border-color 200ms, background 200ms, backdrop-filter 200ms;
  }

  .skip-to-content {
    position: absolute;
    top: -100%;
    left: 16px;
    background: var(--orange);
    color: #fff;
    padding: 8px 16px;
    border-radius: 0 0 8px 8px;
    font-size: 14px;
    font-weight: 600;
    text-decoration: none;
    z-index: 9999;
    transition: top 150ms;
  }

  .skip-to-content:focus {
    top: 0;
  }

  nav.scrolled,
  nav.menu-open {
    border-bottom-color: var(--border);
    background: rgba(7, 11, 20, 0.95);
    backdrop-filter: blur(16px);
    -webkit-backdrop-filter: blur(16px);
  }

  .inner {
    display: flex;
    align-items: center;
    justify-content: space-between;
    height: 64px;
  }

  /* ── Logo ── */
  .logo {
    display: flex;
    align-items: center;
    gap: 12px;
    text-decoration: none;
    flex-shrink: 0;
  }

  .logo-icon {
    display: flex;
    flex-direction: column;
    gap: 3px;
  }

  .bar {
    display: block;
    height: 3px;
    border-radius: 2px;
    background: var(--text-1);
    transition: width 200ms var(--ease-out);
  }

  .bar-1 { width: 20px; }
  .bar-2 { width: 15px; background: var(--cyan); opacity: 0.85; }
  .bar-3 { width: 8px; background: var(--orange); }

  .logo:hover .bar-2 { width: 18px; }
  .logo:hover .bar-3 { width: 12px; }

  .logo-text {
    display: flex;
    flex-direction: column;
    line-height: 1;
  }

  .logo-name {
    font-size: 13px;
    font-weight: 700;
    letter-spacing: 0.1em;
    color: var(--text-1);
  }

  .logo-sub {
    font-size: 10px;
    font-weight: 400;
    letter-spacing: 0.08em;
    color: var(--text-3);
    text-transform: uppercase;
  }

  /* ── Desktop nav links ── */
  .nav-links {
    display: flex;
    align-items: center;
    gap: 28px;
    list-style: none;
  }

  .nav-links a {
    font-size: 14px;
    color: var(--text-2);
    text-decoration: none;
    transition: color 150ms;
    white-space: nowrap;
  }

  .nav-links a:hover { color: var(--text-1); }
  .nav-highlight { color: var(--orange) !important; }

  /* ── Active nav link ── */
  .nav-links a.active {
    color: var(--cyan);
    font-weight: 600;
    position: relative;
  }

  .nav-links a.active::after {
    content: '';
    position: absolute;
    bottom: -4px;
    left: 0;
    right: 0;
    height: 2px;
    background: var(--cyan);
    border-radius: 1px;
    opacity: 0.5;
  }

  .mobile-links a.active {
    color: var(--cyan);
    font-weight: 600;
  }

  .nav-cta {
    display: flex;
    align-items: center;
    gap: 12px;
    flex-shrink: 0;
  }

  /* ── Hamburger button ── */
  .hamburger {
    display: none;
    flex-direction: column;
    justify-content: center;
    gap: 5px;
    width: 40px;
    height: 40px;
    padding: 8px;
    background: none;
    border: 1px solid var(--border);
    border-radius: 8px;
    cursor: pointer;
    flex-shrink: 0;
  }

  .ham-bar {
    display: block;
    width: 100%;
    height: 2px;
    border-radius: 2px;
    background: var(--text-2);
    transition: transform 200ms, opacity 200ms;
  }

  /* ── Mobile menu ── */
  .mobile-backdrop {
    position: fixed;
    inset: 64px 0 0 0;
    background: rgba(7, 11, 20, 0.6);
    backdrop-filter: blur(2px);
    z-index: 98;
    /* button reset */
    border: none;
    padding: 0;
    cursor: default;
    display: block;
    width: 100%;
  }

  .mobile-menu {
    position: absolute;
    top: 64px;
    left: 0;
    right: 0;
    background: rgba(7, 11, 20, 0.98);
    border-bottom: 1px solid var(--border);
    padding: 16px 24px 24px;
    z-index: 99;
    backdrop-filter: blur(16px);
    -webkit-backdrop-filter: blur(16px);
  }

  .mobile-links {
    list-style: none;
    display: flex;
    flex-direction: column;
    gap: 2px;
    margin-bottom: 20px;
  }

  .mobile-links a {
    display: block;
    padding: 12px 8px;
    font-size: 16px;
    font-weight: 500;
    color: var(--text-2);
    text-decoration: none;
    border-radius: 8px;
    transition: background 150ms, color 150ms;
  }

  .mobile-links a:hover,
  .mobile-links a:active {
    color: var(--text-1);
    background: rgba(255, 255, 255, 0.05);
  }

  .mobile-highlight {
    color: var(--orange) !important;
    font-weight: 700 !important;
  }

  .mobile-divider {
    height: 1px;
    background: var(--border);
    margin: 8px 0;
  }

  .mobile-footer {
    display: flex;
    gap: 12px;
  }

  .mobile-footer .btn {
    flex: 1;
    justify-content: center;
  }

  /* ── Responsive breakpoint ── */
  @media (max-width: 860px) {
    .nav-links,
    .nav-cta { display: none; }
    .hamburger { display: flex; }
  }

  @media (max-width: 380px) {
    .logo-sub { display: none; }
  }

  .nav-news,
  .nav-myths {
    font-size: 14px;
    text-decoration: none;
    transition: opacity 150ms;
    white-space: nowrap;
  }
  .nav-news:hover,
  .nav-myths:hover { opacity: 0.75; }

  .nav-news { color: var(--cyan); }
  .nav-myths { color: var(--orange); }

  .nav-news.active { opacity: 0.75; }
  .nav-myths.active { opacity: 0.75; }

  .logo-sub-auto {
    color: var(--cyan);
    display: block;
    font-style: normal;
    letter-spacing: 0.08em;
  }
</style>
