// brand/Bloqr Design System/ui_kits/landing/Pricing.jsx
function Pricing() {
  const tiers = [
    { name: 'Free', price: '$0', period: 'forever', desc: 'The basics, on the house.', cta: 'Get started', primary: false, features: ['1 vendor instance', 'AI flagship list', 'Community support', 'Export anytime'] },
    { name: 'Pro', price: '$4', period: 'per month', desc: 'Roughly the price of a decent coffee.', cta: 'Start 14-day trial', primary: true, features: ['Multi-instance sync', 'Natural language rules', 'AI threat lists', 'Priority support'] },
    { name: 'Pro Max', price: '$12', period: 'per month', desc: 'Less than one mediocre cocktail.', cta: 'Go Max', primary: false, features: ['Everything in Pro', 'API + TypeScript library', 'Custom transformations', 'SLA + audit logs'] },
  ];

  return (
    <section id="pricing" style={{ padding: '80px 0', borderTop: '1px solid var(--border)' }}>
      <div style={{ maxWidth: 1200, margin: '0 auto', padding: '0 24px' }}>
        <SectionHeader
          eyebrow="Pricing"
          title='Honest pricing.<br/>No surprises.'
          aside="Free tier is real, not a 14-day trial pretending. You can bring your own vendor on any tier."
        />
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 20 }}>
          {tiers.map((t, i) => (
            <div key={i}
              style={{
                background: 'var(--bg-surface)',
                border: t.primary ? '1px solid rgba(255,85,0,0.35)' : '1px solid var(--border)',
                borderRadius: 16, padding: 28, position: 'relative',
                boxShadow: t.primary ? '0 0 40px rgba(255,85,0,0.08)' : 'none',
                transition: 'all 200ms var(--ease-out)',
              }}
              onMouseEnter={(e) => { e.currentTarget.style.borderColor = 'var(--border-accent)'; }}
              onMouseLeave={(e) => { e.currentTarget.style.borderColor = t.primary ? 'rgba(255,85,0,0.35)' : 'var(--border)'; }}
            >
              {t.primary && (
                <span style={{
                  position: 'absolute', top: -12, left: 24,
                  padding: '4px 10px', borderRadius: 9999,
                  background: 'var(--orange-500)', color: '#fff',
                  fontSize: 10, fontWeight: 700, letterSpacing: '0.15em', textTransform: 'uppercase',
                }}>Most popular</span>
              )}
              <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.2em', color: 'var(--orange-500)', textTransform: 'uppercase', marginBottom: 8 }}>{t.name}</div>
              <div style={{ display: 'flex', alignItems: 'baseline', gap: 6, marginBottom: 6 }}>
                <span style={{ fontSize: 44, fontWeight: 800, color: 'var(--fg-1)', letterSpacing: '-0.03em', lineHeight: 1 }}>{t.price}</span>
                <span style={{ fontSize: 13, color: 'var(--fg-2)' }}>{t.period}</span>
              </div>
              <p style={{ fontSize: 13, color: 'var(--fg-2)', margin: '0 0 20px' }}>{t.desc}</p>
              <Button variant={t.primary ? 'primary' : 'outline'} size="md" style={{ width: '100%', justifyContent: 'center' }}>{t.cta}</Button>
              <ul style={{ listStyle: 'none', padding: 0, margin: '24px 0 0', display: 'flex', flexDirection: 'column', gap: 10 }}>
                {t.features.map((f, j) => (
                  <li key={j} style={{ display: 'flex', gap: 10, fontSize: 13, color: 'var(--fg-2)', lineHeight: 1.5 }}>
                    <span style={{ color: 'var(--orange-500)', fontWeight: 800 }}>✓</span>{f}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function CtaBanner({ onWaitlist }) {
  return (
    <section style={{ padding: '80px 0', borderTop: '1px solid var(--border)' }}>
      <div style={{ maxWidth: 960, margin: '0 auto', padding: '0 24px' }}>
        <div style={{
          position: 'relative', overflow: 'hidden',
          background: 'linear-gradient(180deg, var(--bg-surface), var(--bg-elevated))',
          border: '1px solid rgba(255,85,0,0.3)', borderRadius: 20,
          padding: '56px 40px', textAlign: 'center',
          boxShadow: '0 0 48px rgba(255,85,0,0.12)',
        }}>
          <div aria-hidden style={{ position: 'absolute', inset: 0, background: 'radial-gradient(ellipse 60% 80% at 50% 0%, rgba(255,85,0,0.1), transparent)', pointerEvents: 'none' }} />
          <div style={{ position: 'relative' }}>
            <h2 style={{ fontSize: 'clamp(2rem, 4vw, 3rem)', fontWeight: 800, letterSpacing: '-0.03em', lineHeight: 1.1, margin: '0 0 16px', color: 'var(--fg-1)' }}>
              Set it. Bloqr it.<br/>
              <span style={{ color: 'var(--orange-500)' }}>Forget it.</span>
            </h2>
            <p style={{ fontSize: '1.05rem', color: 'var(--fg-2)', maxWidth: 480, margin: '0 auto 28px', lineHeight: 1.6 }}>
              Join the waitlist. We'll email you when early access opens — no marketing drip, no follow-ups.
            </p>
            <Button variant="primary" size="lg" onClick={onWaitlist}>Join the waitlist <span aria-hidden>→</span></Button>
          </div>
        </div>
      </div>
    </section>
  );
}

function Footer() {
  return (
    <footer style={{ padding: '56px 0 32px', borderTop: '1px solid var(--border)' }}>
      <div style={{ maxWidth: 1200, margin: '0 auto', padding: '0 24px' }}>
        <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr 1fr 1fr', gap: 40, marginBottom: 40 }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 14 }}>
              <Mark size={28} />
              <span style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 20, color: 'var(--fg-1)', letterSpacing: '-0.01em' }}>Bloqr</span>
            </div>
            <p style={{ fontSize: 13, color: 'var(--fg-2)', lineHeight: 1.6, margin: 0, maxWidth: 320 }}>
              Internet Hygiene. Automated. Built on Cloudflare's edge. Vendor-agnostic. What we don't log can't be leaked.
            </p>
          </div>
          {[
            { title: 'Product', items: ['Features', 'Pricing', 'Changelog', 'Docs'] },
            { title: 'Resources', items: ['VPN Myths', 'Why Not Private', 'Blog', 'RSS'] },
            { title: 'Company', items: ['About', 'Privacy', 'Terms', 'GitHub'] },
          ].map((col, i) => (
            <div key={i}>
              <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.2em', color: 'var(--fg-3)', textTransform: 'uppercase', marginBottom: 14 }}>{col.title}</div>
              <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 8 }}>
                {col.items.map((item, j) => (
                  <li key={j}><a href="#" style={{ fontSize: 13, color: 'var(--fg-2)', textDecoration: 'none' }}>{item}</a></li>
                ))}
              </ul>
            </div>
          ))}
        </div>
        <div style={{ paddingTop: 24, borderTop: '1px solid var(--border)', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 12 }}>
          <span style={{ fontSize: 12, color: 'var(--fg-3)' }}>© 2026 Bloqr · Internet Hygiene. Automated.</span>
          <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--fg-3)' }}>bloqr.ai · v0.80</span>
        </div>
      </div>
    </footer>
  );
}

Object.assign(window, { Pricing, CtaBanner, Footer });

// src/components/Pricing.svelte
<!-- Pricing section -->

<script>
  import { LINKS } from '../config';

  const tiers = [
    {
      name:     'Personal',
      price:    '~$5',
      period:   '/month',
      aside:    'Roughly the price of a decent coffee.',
      tagline:  'For households who just want it handled.',
      cta:      'Join the waitlist',
      href:     '/#waitlist',
      featured: false,
      items: [
        'AI-curated filter list, maintained for you',
        'Works with NextDNS, AdGuard, Pi-hole & more',
        'Multi-device coverage (whole network)',
        'Weekly threat list updates',
        'Email notifications for major incidents',
      ],
    },
    {
      name:     'Pay As You Go',
      price:    '$0.01',
      period:   '/compile',
      aside:    'No subscription. No commitment.',
      tagline:  'Try the full pipeline before you commit. Pay per use via Stripe.',
      cta:      'Start now — no signup',
      get href() { return `${LINKS.pricing}#payg`; },
      featured: false,
      payg:     true,
      items: [
        'No account required to start',
        'Up to 50,000 rules per compile',
        'Up to 5 filter sources per job',
        '500 compiles/day max',
        '7-day output retention',
        'Charged via Stripe — no crypto',
        'Auto-upsell to Pro when it saves you money',
      ],
    },
    {
      name:     'Power User',
      price:    '~$9',
      period:   '/month',
      aside:    'Less than one mediocre cocktail.',
      tagline:  'For people who have opinions about Hagezi vs. OISD.',
      cta:      'Join the waitlist',
      href:     '/#waitlist',
      featured: true,
      items: [
        'Everything in Personal',
        'Custom transformation pipelines',
        'Natural language rule builder',
        'Multi-instance management',
        'API access + JSR package',
        'Priority threat intelligence feed',
        'Full config export (JSON/YAML, version-controllable)',
      ],
    },
    {
      name:     'Developer / Self-Hosted',
      price:    'Free',
      period:   'open-source',
      aside:    'GPL-3.0. It\'s yours.',
      tagline:  'Run it yourself. We won\'t be weird about it.',
      cta:      'View on GitHub',
      href:     'https://github.com/jaypatrick/adblock-compiler',
      featured: false,
      external: true,
      items: [
        'Full compiler source on GitHub',
        'Deno + Node.js + Cloudflare Workers compatible',
        'Self-host anywhere',
        'JSR package: @jk-com/adblock-compiler',
        'OpenAPI spec included',
        'Community support',
      ],
    },
  ];
</script>

<section class="pricing" id="pricing">
  <div class="container">

    <div class="section-header">
      <p class="section-label">Pricing</p>
      <h2 class="section-title">
        Less than your worst<br />
        impulse purchase.
      </h2>
      <p class="section-sub">
        Simple, transparent pricing. Start for free, pay as you go, or subscribe.
        Early access subscribers lock in a discount that stays for the life of the account.
        No crypto. No wallet setup. Just a card.
      </p>
    </div>

    <div class="tiers">
      {#each tiers as tier}
        <div class="tier" class:featured={tier.featured} class:payg={tier.payg}>
          {#if tier.featured}
            <div class="featured-badge">Most popular</div>
          {/if}
          {#if tier.payg}
            <div class="payg-badge">No subscription</div>
          {/if}

          <div class="tier-header">
            <div class="tier-name">{tier.name}</div>
            <div class="tier-price">
              <span class="price">{tier.price}</span>
              <span class="period">{tier.period}</span>
            </div>
            <div class="tier-aside">{tier.aside}</div>
            <p class="tier-tagline">{tier.tagline}</p>
          </div>

          <ul class="feature-list">
            {#each tier.items as item}
              <li>
                <span class="check" aria-hidden="true">✓</span>
                {item}
              </li>
            {/each}
          </ul>

          <a
            href={tier.href}
            class="tier-cta"
            class:primary={tier.featured}
            class:outline={!tier.featured}
            rel={tier.external ? 'noopener noreferrer' : undefined}
            target={tier.external ? '_blank' : undefined}
          >
            {tier.cta}
          </a>
          {#if tier.payg}
            <p class="stripe-note">Powered by Stripe</p>
          {/if}
        </div>
      {/each}
    </div>

    <p class="fine-print">
      All paid tiers include a 30-day money-back guarantee, no questions asked.
      Cancel anytime. The GPL-3.0 open-source version will remain free forever.
    </p>

  </div>
</section>

<style>
  .pricing {
    padding: 96px 0;
    border-top: 1px solid var(--border);
  }

  /* ── Header ── */
  .section-header {
    text-align: center;
    max-width: 600px;
    margin: 0 auto 64px;
  }

  .section-label {
    font-size: 12px;
    font-weight: 600;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: var(--orange);
    margin-bottom: 16px;
  }

  .section-title {
    font-size: clamp(1.75rem, 4vw, 2.5rem);
    font-weight: 700;
    color: var(--text-1);
    line-height: 1.2;
    margin-bottom: 16px;
  }

  .section-sub {
    font-size: 1rem;
    color: var(--text-2);
    line-height: 1.7;
    margin-bottom: 20px;
  }

  /* ── Tiers grid ── */
  .tiers {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 24px;
    align-items: start;
    max-width: 1200px;
    margin: 0 auto;
  }

  .tier {
    position: relative;
    background: var(--bg-surface);
    border: 1px solid var(--border);
    border-radius: 16px;
    padding: 32px 28px;
    display: flex;
    flex-direction: column;
    gap: 24px;
    transition: border-color 150ms;
  }

  .tier:hover { border-color: var(--border-2); }

  .tier.featured {
    border-color: var(--orange);
    background: linear-gradient(
      160deg,
      rgba(255, 85, 0, 0.06) 0%,
      var(--bg-surface) 60%
    );
    box-shadow: 0 0 40px rgba(255, 85, 0, 0.08);
  }

  .featured-badge {
    position: absolute;
    top: -12px;
    left: 50%;
    transform: translateX(-50%);
    background: var(--orange);
    color: #fff;
    font-size: 11px;
    font-weight: 700;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    padding: 4px 14px;
    border-radius: 20px;
    white-space: nowrap;
  }

  .payg-badge {
    position: absolute;
    top: -12px;
    left: 50%;
    transform: translateX(-50%);
    background: var(--cyan);
    color: #000;
    font-size: 11px;
    font-weight: 700;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    padding: 4px 14px;
    border-radius: 20px;
    white-space: nowrap;
  }

  .tier.payg {
    border-color: var(--cyan);
    background: linear-gradient(
      160deg,
      rgba(0, 212, 255, 0.05) 0%,
      var(--bg-surface) 60%
    );
  }

  .stripe-note {
    text-align: center;
    font-size: 11px;
    color: var(--text-3);
    margin-top: -8px;
    letter-spacing: 0.04em;
  }

  /* ── Tier header ── */
  .tier-name {
    font-size: 13px;
    font-weight: 600;
    letter-spacing: 0.06em;
    text-transform: uppercase;
    color: var(--text-3);
  }

  .tier-price {
    display: flex;
    align-items: baseline;
    gap: 4px;
    margin-top: 8px;
  }

  .price {
    font-size: 2.25rem;
    font-weight: 700;
    color: var(--text-1);
    line-height: 1;
  }

  .period {
    font-size: 0.875rem;
    color: var(--text-3);
  }

  .tier-aside {
    font-size: 12px;
    color: var(--text-3);
    font-style: italic;
    margin-top: 4px;
  }

  .tier-tagline {
    font-size: 0.9375rem;
    color: var(--text-2);
    line-height: 1.5;
    margin-top: 4px;
  }

  /* ── Feature list ── */
  .feature-list {
    list-style: none;
    display: flex;
    flex-direction: column;
    gap: 10px;
    flex: 1;
  }

  .feature-list li {
    display: flex;
    gap: 10px;
    font-size: 0.9rem;
    color: var(--text-2);
    line-height: 1.5;
  }

  .check {
    color: var(--orange);
    font-weight: 700;
    flex-shrink: 0;
    font-size: 0.875rem;
    margin-top: 1px;
  }

  .featured .check { color: var(--orange); }

  /* ── CTA buttons ── */
  .tier-cta {
    display: block;
    text-align: center;
    padding: 12px 20px;
    border-radius: 8px;
    font-size: 14px;
    font-weight: 600;
    text-decoration: none;
    transition: all 150ms;
    cursor: pointer;
  }

  .tier-cta.primary {
    background: var(--orange);
    color: #fff;
    box-shadow: 0 0 20px rgba(255, 85, 0, 0.3);
  }
  .tier-cta.primary:hover {
    background: var(--orange-hover);
    box-shadow: 0 0 32px rgba(255, 85, 0, 0.45);
    transform: translateY(-1px);
  }

  .tier-cta.outline {
    background: transparent;
    color: var(--text-1);
    border: 1px solid var(--border-2);
  }
  .tier-cta.outline:hover {
    border-color: var(--text-3);
    background: rgba(255, 255, 255, 0.04);
  }

  /* ── Fine print ── */
  .fine-print {
    text-align: center;
    margin-top: 40px;
    font-size: 13px;
    color: var(--text-3);
    max-width: 480px;
    margin-left: auto;
    margin-right: auto;
    line-height: 1.65;
  }

  /* ── Responsive ── */
  @media (max-width: 1100px) {
    .tiers {
      grid-template-columns: repeat(2, 1fr);
    }
  }

  @media (max-width: 900px) {
    .tiers {
      grid-template-columns: 1fr;
      max-width: 480px;
      margin: 0 auto;
    }
  }

  @media (max-width: 600px) {
    .pricing { padding: 64px 0; }
  }
</style>
